services:
  - type: web
    name: question-for-you
    env: static
    buildCommand: ""
    staticPublishPath: "."
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
